project:
  type: website

website:
  title: "ES104M"
  navbar:
    right:
        
      - href: index.qmd
        text: Home
        icon: fa-home
      - labs.qmd
      - TAs.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto


