---
title: "ES104M - Introduction to Programming"
---

Welcome to the *__Introduction to Programming__* Course. We will be learning C Programming in Linux through this ES104M course.

## Google Classroom Details
The entire batch of 240 students is divided into 4 batches based on your core branch. Please join the respective Google classroom from the below links  

-  [CS Batch](https://classroom.google.com)     
-  [ME Batch](https://classroom.google.com)     
-  [EE Batch](https://classroom.google.com)     
-  [CH/CE Batch](https://classroom.google.com)        

We will be posting the lab exercises, assignments, quizzes in Google classroom, students have to submit their works in classroom for grading and evaluation.

## Piazza Details
All the students are encouraged to join the Introduction to Programming course in piazza for participating in forum discussions    
[Piazza Link](https://piazza.com)

## Grading

This course has both Theory and Lab components and the grading proforma for this course is as follows:

|Weightage Distribution||
|------|------|
|Test - 1 | 10%|
|Test - 2 | 10%|
|Assignments | 10%|
|Final Theory Exam | 25%|
|Weekly Labs | 25%|
|Quizzes | 10%|
|Final Lab Exam | 10%|

The weightage will be formally confirmed after CCM-1



## The Teacher and TAs Team

__Course Instructor:__

*[Dr Raghavendra K](mailto:raghavendra@iittp.ac.in)* - Please [Click Here](https://iittp.ac.in/dr-raghavendra-kanakagiri) to to know more about the faculty

__Head TAs:__    

- [Nagarajan R](mailto:nagarajan@iittp.ac.in) 
- [Suja J](mailto:sujavalan@iittp.ac.in)

__PhD TAs:__ 

- [Aditi Palit](mailto:cs21d001@iittp.ac.in) 
- [Sumukha Bharadwaj](mailto:cs21d003@iittp.ac.in)
- [Tharakeswara Raju](mailto:cs19d503@iittp.ac.in)

__PG TAs:__

- [Ajinkya Sawarkar](cs23s501@iittp.ac.in)
- [Anuroop U Nair](cs23m102@iittp.ac.in)
- [Chiranjeevi B S](cs23m104@iittp.ac.in)
- [Deepak Yadav](cs23m105@iittp.ac.in)
- [Hariom Meena](cs23m106@iittp.ac.in)
- [Jonnalagadda Gopi Krishna](cs23m107@iittp.ac.in)
- [Kuwar Raghvendra Singh](cs23m108@iittp.ac.in)
- [Nitesh Yadav](cs23m110@iittp.ac.in)
- [Vaddempudi Nikhitha](cs23m117@iittp.ac.in)

__Office Hours:__

-  [Office Hours Schedule](link-to-office-hours)


PS: If you have any queries, please post it in Piazza rather than emailing us directly for immediate resolution.

We hope you have a great learning experience in this course!





